package dao;

// Generated 6 févr. 2015 12:12:16 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DemandeId generated by hbm2java
 */
@Embeddable
public class DemandeId implements java.io.Serializable {

	private int idEntreprise;
	private int idSecteur;
	private int idPartenariat;

	public DemandeId() {
	}

	public DemandeId(int idEntreprise, int idSecteur, int idPartenariat) {
		this.idEntreprise = idEntreprise;
		this.idSecteur = idSecteur;
		this.idPartenariat = idPartenariat;
	}

	@Column(name = "idEntreprise", nullable = false)
	public int getIdEntreprise() {
		return this.idEntreprise;
	}

	public void setIdEntreprise(int idEntreprise) {
		this.idEntreprise = idEntreprise;
	}

	@Column(name = "idSecteur", nullable = false)
	public int getIdSecteur() {
		return this.idSecteur;
	}

	public void setIdSecteur(int idSecteur) {
		this.idSecteur = idSecteur;
	}

	@Column(name = "idPartenariat", nullable = false)
	public int getIdPartenariat() {
		return this.idPartenariat;
	}

	public void setIdPartenariat(int idPartenariat) {
		this.idPartenariat = idPartenariat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DemandeId))
			return false;
		DemandeId castOther = (DemandeId) other;

		return (this.getIdEntreprise() == castOther.getIdEntreprise())
				&& (this.getIdSecteur() == castOther.getIdSecteur())
				&& (this.getIdPartenariat() == castOther.getIdPartenariat());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEntreprise();
		result = 37 * result + this.getIdSecteur();
		result = 37 * result + this.getIdPartenariat();
		return result;
	}

}
