package dao;

// Generated 1 mars 2015 20:34:08 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entreprise generated by hbm2java
 */
@Entity
@Table(name = "entreprise", catalog = "cri_db")
public class Entreprise implements java.io.Serializable {

	private Integer idEntreprise;
	private Secteur secteur;
	private Pays pays;
	private Utilisateur utilisateur;
	private String nomEntreprise;
	private String description;
	private String adresseEntreprise;
	private String villeEntreprise;
	private String webEntreprise;
	private String registreCommerce;
	private String nomContact;
	private String prenomContact;
	private String civilité;
	private String fonctionContact;
	private String emailContact;
	private String telContact;
	private String faxContact;
	private boolean valide;
	private Set<Demande> demandes = new HashSet<Demande>(0);

	public Entreprise() {
	}

	public Entreprise(Secteur secteur, Pays pays, String nomEntreprise,
			String description, String adresseEntreprise,
			String villeEntreprise, String registreCommerce, boolean valide) {
		this.secteur = secteur;
		this.pays = pays;
		this.nomEntreprise = nomEntreprise;
		this.description = description;
		this.adresseEntreprise = adresseEntreprise;
		this.villeEntreprise = villeEntreprise;
		this.registreCommerce = registreCommerce;
		this.valide = valide;
	}

	public Entreprise(Secteur secteur, Pays pays, Utilisateur utilisateur,
			String nomEntreprise, String description, String adresseEntreprise,
			String villeEntreprise, String webEntreprise,
			String registreCommerce, String nomContact, String prenomContact,
			String civilité, String fonctionContact, String emailContact,
			String telContact, String faxContact, boolean valide,
			Set<Demande> demandes) {
		this.secteur = secteur;
		this.pays = pays;
		this.utilisateur = utilisateur;
		this.nomEntreprise = nomEntreprise;
		this.description = description;
		this.adresseEntreprise = adresseEntreprise;
		this.villeEntreprise = villeEntreprise;
		this.webEntreprise = webEntreprise;
		this.registreCommerce = registreCommerce;
		this.nomContact = nomContact;
		this.prenomContact = prenomContact;
		this.civilité = civilité;
		this.fonctionContact = fonctionContact;
		this.emailContact = emailContact;
		this.telContact = telContact;
		this.faxContact = faxContact;
		this.valide = valide;
		this.demandes = demandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEntreprise", unique = true, nullable = false)
	public Integer getIdEntreprise() {
		return this.idEntreprise;
	}

	public void setIdEntreprise(Integer idEntreprise) {
		this.idEntreprise = idEntreprise;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSecteur", nullable = false)
	public Secteur getSecteur() {
		return this.secteur;
	}

	public void setSecteur(Secteur secteur) {
		this.secteur = secteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPays", nullable = false)
	public Pays getPays() {
		return this.pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUtilisateur")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "NomEntreprise", nullable = false, length = 50)
	public String getNomEntreprise() {
		return this.nomEntreprise;
	}

	public void setNomEntreprise(String nomEntreprise) {
		this.nomEntreprise = nomEntreprise;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "AdresseEntreprise", nullable = false, length = 200)
	public String getAdresseEntreprise() {
		return this.adresseEntreprise;
	}

	public void setAdresseEntreprise(String adresseEntreprise) {
		this.adresseEntreprise = adresseEntreprise;
	}

	@Column(name = "VilleEntreprise", nullable = false, length = 45)
	public String getVilleEntreprise() {
		return this.villeEntreprise;
	}

	public void setVilleEntreprise(String villeEntreprise) {
		this.villeEntreprise = villeEntreprise;
	}

	@Column(name = "WebEntreprise", length = 50)
	public String getWebEntreprise() {
		return this.webEntreprise;
	}

	public void setWebEntreprise(String webEntreprise) {
		this.webEntreprise = webEntreprise;
	}

	@Column(name = "RegistreCommerce", nullable = false, length = 200)
	public String getRegistreCommerce() {
		return this.registreCommerce;
	}

	public void setRegistreCommerce(String registreCommerce) {
		this.registreCommerce = registreCommerce;
	}

	@Column(name = "NomContact", length = 45)
	public String getNomContact() {
		return this.nomContact;
	}

	public void setNomContact(String nomContact) {
		this.nomContact = nomContact;
	}

	@Column(name = "PrenomContact", length = 45)
	public String getPrenomContact() {
		return this.prenomContact;
	}

	public void setPrenomContact(String prenomContact) {
		this.prenomContact = prenomContact;
	}

	@Column(name = "Civilité", length = 10)
	public String getCivilité() {
		return this.civilité;
	}

	public void setCivilité(String civilité) {
		this.civilité = civilité;
	}

	@Column(name = "FonctionContact", length = 100)
	public String getFonctionContact() {
		return this.fonctionContact;
	}

	public void setFonctionContact(String fonctionContact) {
		this.fonctionContact = fonctionContact;
	}

	@Column(name = "EmailContact", length = 45)
	public String getEmailContact() {
		return this.emailContact;
	}

	public void setEmailContact(String emailContact) {
		this.emailContact = emailContact;
	}

	@Column(name = "TelContact", length = 20)
	public String getTelContact() {
		return this.telContact;
	}

	public void setTelContact(String telContact) {
		this.telContact = telContact;
	}

	@Column(name = "FaxContact", length = 20)
	public String getFaxContact() {
		return this.faxContact;
	}

	public void setFaxContact(String faxContact) {
		this.faxContact = faxContact;
	}

	@Column(name = "valide", nullable = false)
	public boolean isValide() {
		return this.valide;
	}

	public void setValide(boolean valide) {
		this.valide = valide;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entreprise")
	public Set<Demande> getDemandes() {
		return this.demandes;
	}

	public void setDemandes(Set<Demande> demandes) {
		this.demandes = demandes;
	}

}
