package dao;

// Generated 1 mars 2015 20:34:08 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "cri_db")
public class Message implements java.io.Serializable {

	private int idMessage;
	private Utilisateur utilisateur;
	private String nomMessage;
	private String objetMessage;
	private String emailMessage;
	private String contenuMessage;

	public Message() {
	}

	public Message(int idMessage) {
		this.idMessage = idMessage;
	}

	public Message(int idMessage, Utilisateur utilisateur, String nomMessage,
			String objetMessage, String emailMessage, String contenuMessage) {
		this.idMessage = idMessage;
		this.utilisateur = utilisateur;
		this.nomMessage = nomMessage;
		this.objetMessage = objetMessage;
		this.emailMessage = emailMessage;
		this.contenuMessage = contenuMessage;
	}

	@Id
	@Column(name = "idMessage", unique = true, nullable = false)
	public int getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(int idMessage) {
		this.idMessage = idMessage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUtilisateur")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "nomMessage", length = 45)
	public String getNomMessage() {
		return this.nomMessage;
	}

	public void setNomMessage(String nomMessage) {
		this.nomMessage = nomMessage;
	}

	@Column(name = "objetMessage", length = 100)
	public String getObjetMessage() {
		return this.objetMessage;
	}

	public void setObjetMessage(String objetMessage) {
		this.objetMessage = objetMessage;
	}

	@Column(name = "emailMessage", length = 100)
	public String getEmailMessage() {
		return this.emailMessage;
	}

	public void setEmailMessage(String emailMessage) {
		this.emailMessage = emailMessage;
	}

	@Column(name = "ContenuMessage", length = 1000)
	public String getContenuMessage() {
		return this.contenuMessage;
	}

	public void setContenuMessage(String contenuMessage) {
		this.contenuMessage = contenuMessage;
	}

}
