package dao;

// Generated 1 mars 2015 20:34:08 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Partenariat generated by hbm2java
 */
@Entity
@Table(name = "partenariat", catalog = "cri_db")
public class Partenariat implements java.io.Serializable {

	private Integer idPartenariat;
	private String designiation;
	private Set<Demande> demandes = new HashSet<Demande>(0);

	public Partenariat() {
	}

	public Partenariat(String designiation) {
		this.designiation = designiation;
	}

	public Partenariat(String designiation, Set<Demande> demandes) {
		this.designiation = designiation;
		this.demandes = demandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPartenariat", unique = true, nullable = false)
	public Integer getIdPartenariat() {
		return this.idPartenariat;
	}

	public void setIdPartenariat(Integer idPartenariat) {
		this.idPartenariat = idPartenariat;
	}

	@Column(name = "designiation", nullable = false, length = 100)
	public String getDesigniation() {
		return this.designiation;
	}

	public void setDesigniation(String designiation) {
		this.designiation = designiation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partenariat")
	public Set<Demande> getDemandes() {
		return this.demandes;
	}

	public void setDemandes(Set<Demande> demandes) {
		this.demandes = demandes;
	}

}
